Increment 7
mnemchenko/go-shortener pull request #8
Opened 2022-02-20 16:14 UTC by mnemchenko

2022-02-22 17:28 UTC, sergeysergeevru commented on README.md
> +
чтоб у меня в репозиториях так readme поддерживали) 👍

2022-02-22 17:37 UTC, sergeysergeevru commented on internal/storage/file.go
> +	file.Close()
зачем второй file.Close(), если уже есть defer file.Close()?

2022-02-22 17:41 UTC, sergeysergeevru commented on internal/storage/file.go
> +		}
все гуд, просто может такая запись могла бы быть менее перегруженной:
```suggestion
                 if err == io.EOF {
			break
		}
		if err != nil {
			return storage, err
		}
```

2022-02-22 17:42 UTC, sergeysergeevru commented on internal/storage/file.go
> +	file.Close()
Нам defer должно быть достаточно)

2022-02-22 18:09 UTC, sergeysergeevru commented on internal/app/service.go
> +}
синглтон дело хорошее, до поры до времени) Теперь предлагаю начать пользоваться всякими модными словечками типа solid и di. Есть предложение улучшить наш слой app. Давай может создадим Application (имя вымышленное, можно заюзать другое слово)) структуру с методами из твоего app пакета. И вместо того, чтобы объявлять s storage.Storage глобально, инкапсулируем в эту структуру? А прокидывать твой сторадж в структуру будем на основе конфига,  где-нибудь выше. Вообще отпад будет если реализуешь следующий подход где-нибудь в мейн пакете: инициируешь конфиг, на основе конфига создаешь инстанс для Storage, storage прокидываешь в app структуру, а вот уже app структуру юзаешь где-нибудь в хендлере.  Получается как матрешка или в сказке про кощея: репозиторий в application layer, application layer в яйце, яйцо в утке, утка в хендлере. (не удержался от шутки). Сейчас получается ты уже теряешь потихоньку контроль над инициализацией инстанса стораджа, например в тестах. Что если у тебя в окружении будет переменная для FileStorage, а протестировать ты захочешь приложение на memory storage? А так ты сможешь гораздо точнее конфигурировать тесты "руками" прямо в тесте и все контролировать.

2022-02-22 18:14 UTC, sergeysergeevru commented on internal/config/config.go
> +	flagServerAddress := flag.String("a", "", "HTTP server address")
как сейчас норм) можно еще так сделать flag.StringVar(&Config.ServerAddress, "a", "", "HTTP server address") , если я правильно сигнатуру функции помню) Тогда тебе не понадобится проверка ниже на 30 строке. Но Проблемы в текущей имлементации не вижу)

2022-02-22 18:18 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +	}
Пум, пум, тебя останавливает полиция копипысты) Вроде как дупликация кода получается с CreateHandler, Как вариант, можем вынести в какую-нибудь функцию валидации урла, допустим)

2022-02-22 18:30 UTC, sergeysergeevru commented on internal/storage/interface.go
> +type Storage interface {
Гошка использует утиную типизацию. С интерфейсами удобнее работать, когда ты их объявляешь в месте использования, если они не прям супер универсальные как io.Writer и тому подобное. В данном случае можно унести в app  пакет. С моей точки зрения так удобнее делать interface segregation, так как наглядно видно какие методы точно нужны тебе в месте использования, а структурам в пакете storage без особой разниницы под какой интерфейс они должны работать. Однако, это более личный взгляд на мир, у меня нет пока что ссылки что только так и никак иначе)

2022-02-22 18:39 UTC, sergeysergeevru requested changes
Код хороший, структурированный. Чего-то прям критичного не нашел. Я просто хочу предложить чуть больше разобраться с настройкой приложения. Там в комменте описал, как можно конфигурировать через DI, чтобы избавиться от синглтонов, что даст больше контроля в будущем. В чат я скидывал ссылки, на clean и hexagonal architecture я думаю они тебе помогут разобраться. Увидимся! ✌️

2022-02-22 20:33 UTC, mnemchenko commented on internal/storage/file.go
> +	file.Close()
defer сработает только в конце программы, а ее конец блокируется веб-сервером, то есть у нас файл будет висеть открытый, зачем нам это?

а defer просто на всякий случай, основной close без defer

2022-02-22 20:35 UTC, mnemchenko commented on internal/storage/file.go
> +	file.Close()
Тут тот же коммент, что и выше :)

2022-02-22 20:50 UTC, mnemchenko commented on README.md
> +
😀

2022-02-23 12:50 UTC, mnemchenko commented on cmd/shortener/main_test.go
> +	jsonCreateStr, _ := json.Marshal(jsonCreate)
готово

2022-02-23 13:17 UTC, mnemchenko commented on internal/handlers/handlers.go
> +	}
🤦‍♂️ shame on me. Это ж WET :)

2022-02-23 14:59 UTC, mnemchenko commented on internal/app/service.go
> +}
Применил SOLID, использовал везде DI. Теперь модули не связаны
Не стал только конфиг никуда передавать, тк, на мой взгляд, это сильно убавляет прозрачности инициализации всего, что берет данные из этого конфига, если его целиком передавать.
Поэтом передал конкретные значения, нужные для конкретных инициализаций

2022-02-23 15:05 UTC, mnemchenko commented on internal/storage/file.go
> +	file.Close()
defer я поубирал в тех двух местах, что ты написал
потому, что там нужен обычный close, мне кажется
а defer был перестраховкой

2022-02-23 15:10 UTC, mnemchenko commented on internal/config/config.go
> +	flagServerAddress := flag.String("a", "", "HTTP server address")
а он в этом случае не перезатрет ли мои уже заполненные из env поля пустыми значениями флагов?
мне-то надо, чтобы только заполненные значения туда попадали

2022-02-23 19:40 UTC, sergeysergeevru commented on cmd/shortener/main.go
> +	}
небольшой трюк, если вдруг понравится:
```suggestion
	if cnf.FileStorage != "" {
		st, err = storage.NewFileStorage(cnf.FileStorage)
	} else {
		st = storage.NewMemoryStorage()
	}
	if err != nil {
		log.Fatal(err)
	}
```
как то так, если вдруг захочется вложенность избежать :)

2022-02-23 19:47 UTC, sergeysergeevru commented on internal/config/config.go
> +	flagServerAddress := flag.String("a", "", "HTTP server address")
да, хороший поинт. Поиграюсь на досуге. По логике если прокидывать примерно так `flag.StringVar(&Config.ServerAddress, "a", Config.ServerAddress, "HTTP server address")` то получится, что если флага такого нет, то в Config.ServerAddress запишется именно то, что и было в Config.ServerAddress как 3 аргумент по счету. Но да, надо будет проверить в песочнице

2022-02-23 19:51 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +func NewShortenHandlers(app Application) ShortenHandlers {
можно сюда же baseUrl прокинуть

2022-02-23 19:52 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +func NewShortenHandlers(app Application) ShortenHandlers {
тогда не нужен будет сеттер SetBaseURL видимо

2022-02-23 19:52 UTC, sergeysergeevru commented on internal/handlers/handlers.go
> +}
я поискал референсы на метод и не нашел, похоже этот метод не используется больше по коду.

2022-02-23 19:53 UTC, mnemchenko commented on internal/handlers/handlers.go
> +func NewShortenHandlers(app Application) ShortenHandlers {
Сетеры чтобы можно было при желании потом в рантайме поменять

2022-02-23 19:53 UTC, mnemchenko commented on internal/handlers/handlers.go
> +}
Сетеры чтобы можно было при желании потом в рантайме поменять

2022-02-23 20:12 UTC, mnemchenko commented on cmd/shortener/main.go
> +	}
Спасибо 🙂

2022-03-13 20:54 UTC, merged